// ======================================================================
// \title  FppConstantsAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for FPP constants
// ======================================================================

#ifndef GncDeployment_Top_FppConstantsAc_HPP
#define GncDeployment_Top_FppConstantsAc_HPP

#include "Fw/Types/BasicTypes.hpp"

namespace GncDeployment {

  namespace Default {

    enum FppConstant_QUEUE_SIZE {
      QUEUE_SIZE = 10
    };

    enum FppConstant_STACK_SIZE {
      STACK_SIZE = 65536
    };

  }

}

#endif
